name: Daily LOL Bets Automation

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todo dia às 12:00 UTC (09:00 horário de Brasília)
  workflow_dispatch:       # Permite execução manual

jobs:
  run-daily-bets:
    runs-on: ubuntu-latest
    
    steps:
    # Passo 1: Fazer checkout do código
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Passo 3: Instalar dependências
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Passo 4: Criar arquivo .env com variáveis (apenas API_KEY é secreta)
    - name: Create environment file
      env:
        BETSAPI_API_KEY: ${{ secrets.BETSAPI_API_KEY }}
      run: |
        echo "BETSAPI_API_KEY=$BETSAPI_API_KEY" > .env
        echo "CACHE_TTL=300" >> .env
        echo "BASE_URL=https://api.betsapi.com/v1" >> .env
        echo "REQUEST_TIMEOUT=30" >> .env
        echo "✅ Environment file created"

    # Passo 5: Executar script para obter odds dos próximos 10 dias
    - name: Get upcoming odds (10 days)
      run: |
        python get_odds_json.py

    # Passo 6: Executar script para atualizar resultados dos últimos 2 dias
    - name: Get recent match results (2 days)
      run: |
        python get_results_json.py

    # Passo 7: Executar script para atualizar resultados de apostas
    - name: Update bet results
      run: |
        python scripts/db_get_bet_results.py

    # Passo 8: Executar script para verificar novas apostas de valor
    - name: Find value bets
      run: |
        python scripts/ev_bets_analyzer.py

    # Passo 9: Fazer commit e push dos dados atualizados
    - name: Commit and push updated data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/*.db
        git add data/bet365/odds/*.json
        git add lol_results/*.json
        git add reports/*.txt
        git add logs/*.log
        git commit -m "Auto-update: $(date +'%Y-%m-%d %H:%M')" || echo "No changes to commit"
        git push